use crate::elements::ProjectNodeDescription;
use orbtk::prelude::*;

widget!(EditorTabNavigationMock);

impl Template for EditorTabNavigationMock {
    fn template(self, _id: Entity, ctx: &mut BuildContext) -> Self {
        self.name("EditorTabNavigationMock").child(
            Container::new()
                .background("#F0F0F0")
                .child(
                    Stack::new()
                        .orientation("horizontal")
                        .child(
                            Container::new()
                                .style("rule")
                                .padding(5)
                                .child(
                                    Stack::new()
                                        .orientation("horizontal")
                                        .spacing(10)
                                        .child(
                                            ProjectNodeDescription::new()
                                                .text("Test")
                                                .image("src/assets/icons-16/grey_background/class_obj.png")
                                                .build(ctx),
                                        )
                                        .child(
                                            ImageWidget::new()
                                                .image("src/assets/icons-16/grey_background/cross.png")
                                                .build(ctx),
                                        )
                                        .build(ctx),
                                )
                                .build(ctx),
                        )
                        .child(
                            Container::new()
                                .style("rule")
                                .padding(5)
                                .child(
                                    Stack::new()
                                        .orientation("horizontal")
                                        .spacing(10)
                                        .child(
                                            ProjectNodeDescription::new()
                                                .text("Test")
                                                .image("src/assets/icons-16/grey_background/class_obj.png")
                                                .build(ctx),
                                        )
                                        .child(
                                            ImageWidget::new()
                                                .image("src/assets/icons-16/grey_background/cross.png")
                                                .build(ctx),
                                        )
                                        .build(ctx),
                                )
                                .build(ctx),
                        )
                        .child(
                            Container::new()
                                .style("rule")
                                .padding(5)
                                .child(
                                    Stack::new()
                                        .spacing(10)
                                        .orientation("horizontal")
                                        .child(
                                            ProjectNodeDescription::new()
                                                .text("Test")
                                                .image("src/assets/icons-16/grey_background/class_obj.png")
                                                .build(ctx),
                                        )
                                        .child(
                                            ImageWidget::new()
                                                .image("src/assets/icons-16/grey_background/cross.png")
                                                .build(ctx),
                                        )
                                        .build(ctx),
                                )
                                .build(ctx),
                        )
                        .child(
                            Container::new()
                                .style("rule")
                                .padding(5)
                                .child(
                                    Stack::new()
                                        .orientation("horizontal")
                                        .spacing(10)
                                        .child(
                                            ProjectNodeDescription::new()
                                                .text("Test")
                                                .image("src/assets/icons-16/grey_background/class_obj.png")
                                                .build(ctx),
                                        )
                                        .child(
                                            ImageWidget::new()
                                                .image("src/assets/icons-16/grey_background/cross.png")
                                                .build(ctx),
                                        )
                                        .build(ctx),
                                )
                                .build(ctx),
                        )
                        .child(
                            Container::new()
                                .style("rule")
                                .padding(5)
                                .child(
                                    Stack::new()
                                        .orientation("horizontal")
                                        .spacing(10)
                                        .child(
                                            ProjectNodeDescription::new()
                                                .text("Test")
                                                .image("src/assets/icons-16/grey_background/class_obj.png")
                                                .build(ctx),
                                        )
                                        .child(
                                            ImageWidget::new()
                                                .image("src/assets/icons-16/grey_background/cross.png")
                                                .build(ctx),
                                        )
                                        .build(ctx),
                                )
                                .build(ctx),
                        )
                        .build(ctx),
                )
                .build(ctx),
        )
    }
}
